# Generated by Django 6.0.4 on 2026-05-01 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0003_userattribute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAttribute',
            new_name='UserAttributes',
        ),
    ]
