# Generated by Django 6.0.4 on 2026-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0004_rename_userattribute_userattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='measures',
            name='activity_level',
            field=models.IntegerField(default=1, verbose_name='Nível de atividade'),
        ),
    ]
